import http.server
import socketserver
from urllib.parse import urlparse
from urllib.parse import parse_qs
import os

def env2html(env):
    return("<br>"+env+"="+str(os.getenv(env)))

class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Extract query param
        name = 'World'
        query_components = parse_qs(urlparse(self.path).query)
        if 'name' in query_components:
            name = query_components["name"][0]
        envs="<br>"
        for k,v in sorted(os.environ.items()):
            envs=envs+k+" = "+v+"<br>"

        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body>"+envs+"</body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return

# Create an object of the above class
handler_object = MyHttpRequestHandler

PORT = 8000
my_server = socketserver.TCPServer(("", PORT), handler_object)

# Star the server
my_server.serve_forever()
